#!/usr/bin/env python3
"""Génère le catalogue initial de plugins VST/MAO."""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

from validate import is_allowed_url, slugify

ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATHS = [
    ROOT / "data" / "plugins.json",
    ROOT / "web" / "data" / "plugins.json",
]

CATALOG_VERSION = "1.0.0"
TODAY = date.today().isoformat()


def plugin(
    name: str,
    developer: str,
    category: str,
    official_url: str,
    *,
    is_free: bool,
    price_eur: float | None = None,
    formats: list[str] | None = None,
    platforms: list[str] | None = None,
    description: str = "",
) -> dict:
    if not is_allowed_url(official_url):
        raise ValueError(f"URL non autorisée pour {name}: {official_url}")
    slug = slugify(name)
    return {
        "id": slug,
        "slug": slug,
        "name": name,
        "developer": developer,
        "category": category,
        "formats": formats or ["VST3", "AU"],
        "platforms": platforms or ["windows", "macos"],
        "isFree": is_free,
        "priceEur": None if is_free else price_eur,
        "officialUrl": official_url,
        "description": description,
        "discoveredAt": TODAY,
        "source": "manual",
    }


SEED_PLUGINS: list[dict] = [
    plugin("Vital", "Matt Tytel", "synth", "https://vital.audio/", is_free=True, platforms=["windows", "macos", "linux"], description="Synthé wavetable gratuit et puissant, idéal pour la production moderne."),
    plugin("Surge XT", "Surge Synth Team", "synth", "https://surge-synthesizer.github.io/", is_free=True, platforms=["windows", "macos", "linux"], description="Synthé open-source hybride avec une bibliothèque de presets immense."),
    plugin("Helm", "Matt Tytel", "synth", "https://tytel.org/helm", is_free=True, platforms=["windows", "macos", "linux"], description="Synthé polyphonique gratuit au son clair et polyvalent."),
    plugin("Odin 2", "TheWaveWarden", "synth", "https://www.thewavewarden.com/product/odin2/", is_free=True, description="Synthé analogique virtuel gratuit avec trois oscillateurs."),
    plugin("Dexed", "Digital Suburban", "synth", "https://asb2m10.github.io/dexed/", is_free=True, platforms=["windows", "macos", "linux"], description="Émulation gratuite du légendaire synthé Yamaha DX7."),
    plugin("TAL-NoiseMaker", "TAL Software", "synth", "https://tal-software.com/products/tal-noisemaker", is_free=True, description="Synthé virtuel analogique gratuit de TAL."),
    plugin("Komplete Start", "Native Instruments", "sampler", "https://www.native-instruments.com/en/products/komplete/bundles/komplete-start/", is_free=True, description="Bundle gratuit avec Kontakt Player, synthés et effets NI."),
    plugin("Spitfire LABS", "Spitfire Audio", "orchestral", "https://www.spitfireaudio.com/labs", is_free=True, description="Instruments orchestraux et textures gratuits en qualité studio."),
    plugin("Decent Sampler", "Decent Samples", "sampler", "https://www.decentsamples.com/product/decent-sampler-plugin/", is_free=True, description="Sampler gratuit compatible avec la bibliothèque Decent Sampler."),
    plugin("Ample Guitar M Lite II", "Ample Sound", "guitar", "https://www.amplesound.net/en/pro-pd.asp?id=7", is_free=True, description="Guitare acoustique Martin D-41 en version lite gratuite."),
    plugin("Sforzando", "Plogue", "sampler", "https://www.plogue.com/products/sforzando.html", is_free=True, description="Lecteur SFZ gratuit pour instruments orchestraux."),
    plugin("Valhalla Supermassive", "Valhalla DSP", "reverb", "https://valhalladsp.com/shop/reverb/valhalla-supermassive/", is_free=True, description="Réverb et delay cosmiques gratuits, très appréciés en production."),
    plugin("Valhalla Space Modulator", "Valhalla DSP", "modulation", "https://valhalladsp.com/shop/modulation/valhalla-space-modulator/", is_free=True, description="Modulateur de flanger gratuit au caractère unique."),
    plugin("TDR Nova", "Tokyo Dawn Labs", "eq", "https://www.tokyodawn.net/tdr-nova/", is_free=True, description="Égaliseur dynamique paramétrique gratuit très complet."),
    plugin("TDR Kotelnikov", "Tokyo Dawn Labs", "compressor", "https://www.tokyodawn.net/tdr-kotelnikov/", is_free=True, description="Compresseur transparent gratuit pour le mixage."),
    plugin("TDR VOS SlickEQ", "Tokyo Dawn Labs", "eq", "https://www.tokyodawn.net/tdr-vos-slickeq/", is_free=True, description="Égaliseur musical gratuit inspiré des consoles vintage."),
    plugin("TDR Molotok", "Tokyo Dawn Labs", "compressor", "https://www.tokyodawn.net/tdr-molotok/", is_free=True, description="Compresseur coloré gratuit pour donner du caractère."),
    plugin("TAL-Reverb-4", "TAL Software", "reverb", "https://tal-software.com/products/tal-reverb-4", is_free=True, description="Réverbération algorithmique gratuite simple et efficace."),
    plugin("TAL-Chorus-LX", "TAL Software", "modulation", "https://tal-software.com/products/tal-chorus-lx", is_free=True, description="Chorus gratuit inspiré du Roland Juno-60."),
    plugin("OTT", "Xfer Records", "compressor", "https://xferrecords.com/freeware", is_free=True, description="Compresseur multibande gratuit iconique en EDM."),
    plugin("Krush", "Kilohearts", "distortion", "https://kilohearts.com/products/krush", is_free=True, description="Distorsion bitcrush gratuite pour des textures lo-fi."),
    plugin("ChowMatrix", "ChowDSP", "delay", "https://chowdsp.com/products/", is_free=True, platforms=["windows", "macos", "linux"], description="Delay modulaire gratuit open-source aux possibilités étendues."),
    plugin("ChowTape", "ChowDSP", "distortion", "https://chowdsp.com/products/", is_free=True, description="Émulation de bande magnétique gratuite open-source."),
    plugin("MeldaProduction Free Bundle", "MeldaProduction", "utility", "https://www.meldaproduction.com/MFreeFXBundle", is_free=True, description="Suite de plus de 30 plugins gratuits pour le mixage et le mastering."),
    plugin("Airwindows Consolidated", "Airwindows", "utility", "https://airwindows.com/", is_free=True, description="Collection massive de plugins gratuits pour le mixage analogique."),
    plugin("Analog Obsession LALA", "Analog Obsession", "compressor", "https://analogobsession.com/", is_free=True, description="Compresseur LA-2A gratuit de la collection Analog Obsession."),
    plugin("Analog Obsession Rare", "Analog Obsession", "eq", "https://analogobsession.com/", is_free=True, description="Égaliseur Pultec gratuit de style vintage."),
    plugin("Ignite Amps Emissary", "Ignite Amps", "guitar", "https://www.igniteamps.com/", is_free=True, description="Simulateur de tête d'ampli guitare gratuite très populaire."),
    plugin("Neural Amp Modeler", "Steven Atkinson", "guitar", "https://www.neuralampmodeler.com/", is_free=True, description="Plateforme gratuite de modélisation d'amplis par IA."),
    plugin("Spitfire BBC Symphony Orchestra Discover", "Spitfire Audio", "orchestral", "https://www.spitfireaudio.com/bbc-so-discover", is_free=True, description="Orchestre symphonique BBC gratuit pour la composition."),
    plugin("PianoTeq 8 Trial", "Modartt", "piano", "https://www.pianoteq.com/", is_free=False, price_eur=159.0, description="Piano acoustique modélisé physiquement, référence du marché."),
    plugin("Serum", "Xfer Records", "synth", "https://xferrecords.com/products/serum", is_free=False, price_eur=189.0, description="Synthé wavetable leader pour la production électronique."),
    plugin("FabFilter Pro-Q 3", "FabFilter", "eq", "https://www.fabfilter.com/products/pro-q-3-equalizer-plug-in", is_free=False, price_eur=179.0, description="Égaliseur dynamique de référence pour le mixage professionnel."),
    plugin("FabFilter Pro-C 2", "FabFilter", "compressor", "https://www.fabfilter.com/products/pro-c-2-compressor-plug-in", is_free=False, price_eur=179.0, description="Compresseur polyvalent avec modes VCA, FET et opto."),
    plugin("FabFilter Pro-L 2", "FabFilter", "mastering", "https://www.fabfilter.com/products/pro-l-2-limiter-plug-in", is_free=False, price_eur=199.0, description="Limiteur transparent de référence pour le mastering."),
    plugin("Valhalla VintageVerb", "Valhalla DSP", "reverb", "https://valhalladsp.com/shop/reverb/valhalla-vintageverb/", is_free=False, price_eur=50.0, description="Réverbération vintage inspirée des années 70 et 80."),
    plugin("Valhalla Room", "Valhalla DSP", "reverb", "https://valhalladsp.com/shop/reverb/valhalla-room/", is_free=False, price_eur=50.0, description="Réverbération algorithmique claire et flexible."),
    plugin("Soundtoys Decapitator", "Soundtoys", "distortion", "https://www.soundtoys.com/product/decapitator/", is_free=False, price_eur=199.0, description="Saturation analogique au caractère affirmé."),
    plugin("Soundtoys EchoBoy", "Soundtoys", "delay", "https://www.soundtoys.com/product/echoboy/", is_free=False, price_eur=199.0, description="Delay vintage avec émulation de bandes et de pédales."),
    plugin("Omnisphere", "Spectrasonics", "synth", "https://www.spectrasonics.net/products/omnisphere/", is_free=False, price_eur=479.0, description="Synthé hybride premium avec une bibliothèque sonore immense."),
    plugin("Kontakt 7", "Native Instruments", "sampler", "https://www.native-instruments.com/en/products/komplete/samplers/kontakt-7/", is_free=False, price_eur=299.0, description="Sampler industriel compatible avec des milliers de bibliothèques."),
    plugin("Massive X", "Native Instruments", "synth", "https://www.native-instruments.com/en/products/komplete/synths/massive-x/", is_free=False, price_eur=199.0, description="Synthé wavetable moderne successeur du légendaire Massive."),
    plugin("Arturia V Collection", "Arturia", "synth", "https://www.arturia.com/products/software-instruments/v-collection/", is_free=False, price_eur=599.0, description="Collection d'émulations de synthés et pianos classiques."),
    plugin("u-he Diva", "u-he", "synth", "https://u-he.com/products/diva/", is_free=False, price_eur=179.0, description="Synthé analogique virtuel au son chaud et authentique."),
    plugin("u-he Hive 2", "u-he", "synth", "https://u-he.com/products/hive/", is_free=False, price_eur=99.0, description="Synthé moderne compact avec tables d'ondes et filtres flexibles."),
    plugin("Sylenth1", "LennarDigital", "synth", "https://www.lennardigital.com/", is_free=False, price_eur=179.0, description="Synthé analogique virtuel iconique en house et trance."),
    plugin("Phase Plant", "Kilohearts", "synth", "https://kilohearts.com/products/phase_plant", is_free=False, price_eur=149.0, description="Synthé modulaire semi-modulaire très flexible."),
    plugin("Scaler 2", "Plugin Boutique", "utility", "https://www.pluginboutique.com/products/2-Scaler-2", is_free=False, price_eur=59.0, description="Assistant d'accords et de composition pour producteurs."),
    plugin("iZotope Ozone 11 Elements", "iZotope", "mastering", "https://www.izotope.com/en/shop/ozone-elements", is_free=False, price_eur=129.0, description="Suite de mastering assistée par IA en version Elements."),
    plugin("iZotope Neutron 4", "iZotope", "utility", "https://www.izotope.com/en/shop/neutron", is_free=False, price_eur=249.0, description="Assistant de mixage intelligent avec analyse spectrale."),
    plugin("iZotope RX 11 Elements", "iZotope", "vocal", "https://www.izotope.com/en/shop/rx-elements", is_free=False, price_eur=129.0, description="Réparation audio pour voix, podcasts et enregistrements."),
    plugin("Soothe2", "oeksound", "eq", "https://oeksound.com/plugins/soothe2/", is_free=False, price_eur=219.0, description="Suppresseur de résonances dynamique très populaire."),
    plugin("Spiff", "oeksound", "eq", "https://oeksound.com/plugins/spiff/", is_free=False, price_eur=149.0, description="Outil de contrôle des transitoires haute fréquence."),
    plugin("Gullfoss", "Soundtheory", "eq", "https://www.soundtheory.com/gullfoss", is_free=False, price_eur=199.0, description="Égaliseur intelligent qui adapte le spectre automatiquement."),
    plugin("Sonible smart:EQ 4", "Sonible", "eq", "https://www.sonible.com/smarteq4/", is_free=False, price_eur=129.0, description="Égaliseur assisté par IA pour un équilibre rapide."),
    plugin("Sonible pure:unmask", "Sonible", "utility", "https://www.sonible.com/pureunmask/", is_free=False, price_eur=89.0, description="Outil de séparation spectrale pour clarifier le mix."),
    plugin("Eventide Blackhole", "Eventide", "reverb", "https://www.eventideaudio.com/plug-ins/blackhole/", is_free=False, price_eur=99.0, description="Réverbération spatiale immense pour textures atmosphériques."),
    plugin("Eventide H910 Harmonizer", "Eventide", "modulation", "https://www.eventideaudio.com/plug-ins/h910-harmonizer/", is_free=False, price_eur=99.0, description="Harmonizer vintage légendaire des années 70."),
    plugin("Softube Tape", "Softube", "distortion", "https://www.softube.com/tape", is_free=False, price_eur=99.0, description="Émulation de bande magnétique pour chaleur analogique."),
    plugin("Softube Console 1", "Softube", "utility", "https://www.softube.com/console1", is_free=False, price_eur=449.0, description="Écosystème de mixage hardware + software avec émulations SSL."),
    plugin("Waves CLA-2A", "Waves", "compressor", "https://www.waves.com/plugins/cla-2a-compressor-limiter", is_free=False, price_eur=35.0, description="Compresseur opto LA-2A émulé par Chris Lord-Alge."),
    plugin("Waves H-Reverb", "Waves", "reverb", "https://www.waves.com/plugins/h-reverb-hybrid-reverb", is_free=False, price_eur=35.0, description="Réverbération hybride avec algorithmes et impulses."),
    plugin("Slate Digital Virtual Mix Rack", "Slate Digital", "utility", "https://slatedigital.com/virtual-mix-rack/", is_free=False, price_eur=149.0, description="Chaîne de modules de mixage modulaire Slate Digital."),
    plugin("Slate Digital FG-X", "Slate Digital", "mastering", "https://slatedigital.com/fg-x/", is_free=False, price_eur=199.0, description="Limiteur de mastering avec détection intelligente."),
    plugin("Output Portal", "Output", "distortion", "https://output.com/products/portal", is_free=False, price_eur=199.0, description="Effet de grain et de manipulation spectrale créatif."),
    plugin("Output Arcade", "Output", "sampler", "https://output.com/products/arcade", is_free=False, price_eur=10.0, description="Sampler loop cloud avec contenu renouvelé mensuellement."),
    plugin("Unfiltered Audio BYOME", "Unfiltered Audio", "distortion", "https://www.unfilteredaudio.com/byome", is_free=False, price_eur=99.0, description="Multi-effet modulaire programmable pour le sound design."),
    plugin("Unfiltered Audio Sandman Pro", "Unfiltered Audio", "delay", "https://www.unfilteredaudio.com/sandman-pro", is_free=False, price_eur=99.0, description="Delay granulaire pour textures rythmiques et glitch."),
    plugin("Baby Audio BA-1", "Baby Audio", "synth", "https://babyaud.io/ba-1", is_free=False, price_eur=79.0, description="Synthé inspiré du Yamaha CS-01 au caractère lo-fi."),
    plugin("Baby Audio Super VHS", "Baby Audio", "distortion", "https://babyaud.io/super-vhs", is_free=False, price_eur=49.0, description="Effet lo-fi multi-bandes pour ambiance cassette rétro."),
    plugin("Denise Audio Perfect Room 2", "Denise Audio", "reverb", "https://www.denise.io/perfect-room-2", is_free=False, price_eur=79.0, description="Réverbération avec contrôle spatial précis."),
    plugin("Denise Audio Bass XL", "Denise Audio", "utility", "https://www.denise.io/bass-xl", is_free=False, price_eur=49.0, description="Enhancer de basses pour des low-end percutants."),
    plugin("Klevgrand Brusfri", "Klevgrand", "utility", "https://klevgrand.se/products/brusfri", is_free=False, price_eur=49.0, description="Réducteur de bruit simple et efficace pour l'enregistrement."),
    plugin("Klevgrand Pana", "Klevgrand", "utility", "https://klevgrand.se/products/pana", is_free=False, price_eur=29.0, description="Outil de placement stéréo et de panoramique avancé."),
    plugin("Goodhertz DC19", "Goodhertz", "modulation", "https://goodhertz.co/dc19/", is_free=False, price_eur=29.0, description="Chorus et vibrato au grain vintage."),
    plugin("Goodhertz Tupe", "Goodhertz", "distortion", "https://goodhertz.co/tupe/", is_free=False, price_eur=29.0, description="Saturation de tubes subtile pour le mixage."),
    plugin("AudioThing Dials", "AudioThing", "distortion", "https://www.audiothing.net/effects/dials/", is_free=False, price_eur=49.0, description="Distorsion inspirée des pédales de guitare vintage."),
    plugin("AudioThing Speakers", "AudioThing", "utility", "https://www.audiothing.net/effects/speakers/", is_free=False, price_eur=49.0, description="Émulation de haut-parleurs pour des textures lo-fi."),
    plugin("AudioModern Riffer", "AudioModern", "utility", "https://audiomodern.com/shop/plugins/riffer/", is_free=False, price_eur=59.0, description="Générateur de riffs et mélodies MIDI aléatoires."),
    plugin("Wave Alchemy Pulse", "Wave Alchemy", "drums", "https://www.wavealchemy.co.uk/pulse/", is_free=False, price_eur=99.0, description="Machine à rythmes avec échantillons de boîtes vintage."),
    plugin("Wave Alchemy Triaz", "Wave Alchemy", "drums", "https://www.wavealchemy.co.uk/triaz/", is_free=False, price_eur=149.0, description="Plugin de drums avec des kits modernes et vintage."),
    plugin("XLN Audio Addictive Drums 2", "XLN Audio", "drums", "https://www.xlnaudio.com/products/addictive_drums_2", is_free=False, price_eur=149.0, description="Batterie acoustique échantillonnée très réaliste."),
    plugin("XLN Audio Addictive Keys", "XLN Audio", "piano", "https://www.xlnaudio.com/products/addictive_keys", is_free=False, price_eur=149.0, description="Pianos échantillonnés avec options de micros multiples."),
    plugin("Toontrack EZdrummer 3", "Toontrack", "drums", "https://www.toontrack.com/product/ezdrummer-3/", is_free=False, price_eur=149.0, description="Batterie virtuelle simple et rapide pour la composition."),
    plugin("Toontrack Superior Drummer 3", "Toontrack", "drums", "https://www.toontrack.com/product/superior-drummer-3/", is_free=False, price_eur=399.0, description="Batterie acoustique haut de gamme pour production pro."),
    plugin("Steven Slate Drums 5", "Steven Slate Drums", "drums", "https://stevenslatedrums.com/ssd5/", is_free=False, price_eur=149.0, description="Batterie avec échantillons de kits enregistrés en studio."),
    plugin("BFD3", "FXpansion", "drums", "https://www.fxpansion.com/products/bfd3", is_free=False, price_eur=149.0, description="Moteur de batterie acoustique détaillé et personnalisable."),
    plugin("Shreddage 3 Stratus", "Impact Soundworks", "guitar", "https://impactsoundworks.com/shreddage-3-stratus", is_free=False, price_eur=159.0, description="Guitare électrique échantillonnée pour rock et metal."),
    plugin("Neural DSP Archetype: Plini", "Neural DSP", "guitar", "https://neuraldsp.com/plugins/archetype-plini", is_free=False, price_eur=99.0, description="Suite d'amplis et d'effets guitare signée Plini."),
    plugin("Neural DSP Archetype: Gojira", "Neural DSP", "guitar", "https://neuraldsp.com/plugins/archetype-gojira", is_free=False, price_eur=99.0, description="Amplis et pédales pour metal moderne signés Gojira."),
    plugin("Positive Grid BIAS FX 2", "Positive Grid", "guitar", "https://www.positivegrid.com/bias-fx", is_free=False, price_eur=149.0, description="Plateforme d'amplis et d'effets guitare modulaire."),
    plugin("Overloud TH-U", "Overloud", "guitar", "https://www.overloud.com/products/th-u", is_free=False, price_eur=179.0, description="Simulateur d'amplis avec modélisation Rig Player."),
    plugin("IK Multimedia AmpliTube 5", "IK Multimedia", "guitar", "https://www.ikmultimedia.com/products/amplitube5/", is_free=False, price_eur=199.0, description="Suite complète de simulation d'amplis et d'effets guitare."),
    plugin("Nectar 3 Plus", "iZotope", "vocal", "https://www.izotope.com/en/shop/nectar", is_free=False, price_eur=249.0, description="Chaîne de traitement vocale complète pour le mixage."),
    plugin("Auto-Tune Pro", "Antares", "vocal", "https://www.antarestech.com/products/auto-tune", is_free=False, price_eur=399.0, description="Correction de hauteur et effet vocal de référence."),
    plugin("Synchro Arts ReVoice Pro 5", "Synchro Arts", "vocal", "https://www.synchroarts.com/revoice-pro", is_free=False, price_eur=599.0, description="Alignement vocal et harmonisation professionnelle."),
    plugin("Accusonus ERA Bundle 6", "Accusonus", "vocal", "https://accusonus.com/products/era-bundle", is_free=False, price_eur=149.0, description="Outils de nettoyage audio pour voix et podcasts."),
    plugin("Sonarworks SoundID Reference", "Sonarworks", "analyzer", "https://www.sonarworks.com/soundid-reference", is_free=False, price_eur=249.0, description="Calibration de monitoring pour un mixage plus précis."),
    plugin("Plugin Doctor", "DDMF", "analyzer", "https://ddmf.eu/plugin-doctor/", is_free=False, price_eur=49.0, description="Analyseur de courbes et de phase pour plugins et hardware."),
    plugin("Voxengo SPAN", "Voxengo", "analyzer", "https://www.voxengo.com/product/span/", is_free=True, description="Analyseur spectral gratuit très utilisé en mastering."),
    plugin("Youlean Loudness Meter 2", "Youlean", "analyzer", "https://youlean.co/youlean-loudness-meter/", is_free=True, description="Mesure de loudness LUFS gratuite conforme aux standards broadcast."),
    plugin("TB Pro Audio mvMeter2", "TB Pro Audio", "analyzer", "https://www.tbproaudio.de/products/mvmeter2", is_free=True, description="VU-mètre gratuit pour surveiller les niveaux."),
    plugin("OrilRiver", "Denis Tihanov", "reverb", "https://www.tokyodawn.net/other/", is_free=True, description="Réverbération algorithmique gratuite à convolution modulable."),
    plugin("LoudMax", "Thomas Mundt", "mastering", "https://loudmax.blogspot.com/", is_free=True, description="Limiteur brickwall gratuit simple et transparent."),
    plugin("Glitch2", "Illformed", "sampler", "https://www.illformed.com/", is_free=False, price_eur=49.0, description="Sampler glitch pour productions IDM et expérimentales."),
    plugin("Cable Guys ShaperBox 3", "Cableguys", "utility", "https://www.cableguys.com/shaperbox.html", is_free=False, price_eur=99.0, description="Suite de modulation rythmique pour tous les paramètres."),
    plugin("Cable Guys Pancake 2", "Cableguys", "modulation", "https://www.cableguys.com/pancake.html", is_free=True, description="Auto-pan gratuit avec formes de modulation créatives."),
    plugin("InstaComposer 3", "W.A. Production", "utility", "https://www.waproduction.com/plugins/instacomposer-3", is_free=False, price_eur=59.0, description="Générateur de compositions MIDI par IA."),
    plugin("Tracktion Waveform Free", "Tracktion", "utility", "https://www.tracktion.com/products/waveform-free", is_free=True, description="DAW complète gratuite avec suite d'effets intégrée."),
    plugin("Reaper", "Cockos", "utility", "https://www.reaper.fm/", is_free=False, price_eur=60.0, description="DAW légère et puissante avec licence abordable."),
    plugin("Ableton Live 12 Intro", "Ableton", "utility", "https://www.ableton.com/en/live/", is_free=False, price_eur=99.0, description="DAW iconique pour la production électronique live."),
    plugin("FL Studio Fruity Edition", "Image-Line", "utility", "https://www.image-line.com/fl-studio", is_free=False, price_eur=99.0, description="DAW populaire pour beatmaking et production hip-hop."),
    plugin("Reason Rack Plugin", "Reason Studios", "utility", "https://www.reasonstudios.com/reason-rack-plugin", is_free=False, price_eur=99.0, description="Rack Reason utilisable comme plugin dans votre DAW."),
    plugin("Spire", "Reveal Sound", "synth", "https://reveal-sound.com/", is_free=False, price_eur=189.0, description="Synthé EDM puissant pour leads et basses modernes."),
    plugin("Pigments", "Arturia", "synth", "https://www.arturia.com/products/software-instruments/pigments/", is_free=False, price_eur=199.0, description="Synthé wavetable et analogique avec interface visuelle."),
    plugin("Analog Lab V", "Arturia", "synth", "https://www.arturia.com/products/software-instruments/analoglab/", is_free=False, price_eur=199.0, description="Collection de presets des synthés Arturia en un seul plugin."),
    plugin("RC-20 Retro Color", "XLN Audio", "distortion", "https://www.xlnaudio.com/products/rc-20_retro_color", is_free=False, price_eur=99.0, description="Effet lo-fi rétro pour textures vintage et usées."),
    plugin("Portal", "Output", "distortion", "https://output.com/products/portal", is_free=False, price_eur=199.0, description="Effet granulaire pour sound design expérimental."),
    plugin("SubLab XL", "Future Audio Workshop", "synth", "https://sublabxl.com/", is_free=False, price_eur=59.0, description="Synthé de sub-basses pour trap et hip-hop."),
    plugin("Initial Audio Sektor", "Initial Audio", "synth", "https://initialaudio.com/sektor/", is_free=False, price_eur=99.0, description="Synthé wavetable moderne avec interface 3D."),
    plugin("D16 Lush 2", "D16 Group", "synth", "https://d16.pl/lush2", is_free=False, price_eur=99.0, description="Synthé pad lush pour ambient et soundscapes."),
    plugin("Sugar Bytes Effectrix", "Sugar Bytes", "modulation", "https://sugar-bytes.de/products/effectrix", is_free=False, price_eur=99.0, description="Effet multi-tranches pour séquençage rythmique créatif."),
    plugin("Sugar Bytes Looperator", "Sugar Bytes", "modulation", "https://sugar-bytes.de/products/looperator", is_free=False, price_eur=99.0, description="Effet looper et modulateur pour performances live."),
    plugin("Audiority L12X", "Audiority", "guitar", "https://www.audiority.com/l12x", is_free=False, price_eur=49.0, description="Amplificateur Solid State Logic pour guitare et bass."),
    plugin("Mercuriall U530", "Mercuriall", "guitar", "https://mercuriall.com/", is_free=True, description="Simulateur de préampli Friedman BE-100 gratuit."),
    plugin("STL Tones AmpHub", "STL Tones", "guitar", "https://stltones.com/", is_free=False, price_eur=99.0, description="Plateforme d'amplis guitare avec packs d'artistes."),
    plugin("Swam Saxophones", "Audio Modeling", "orchestral", "https://www.swamitaly.it/products/swam-saxophones/", is_free=False, price_eur=149.0, description="Saxophones modélisés physiquement pour expression MIDI."),
    plugin("SWAM Violin", "Audio Modeling", "orchestral", "https://www.swamitaly.it/products/swam-violin/", is_free=False, price_eur=149.0, description="Violon solo modélisé avec contrôle expressif continu."),
    plugin("EastWest Hollywood Orchestra", "EastWest", "orchestral", "https://www.soundsonline.com/Hollywood-Orchestra", is_free=False, price_eur=499.0, description="Orchestre symphonique Hollywood pour la composition ciné."),
    plugin("Orchestral Tools Berlin Strings", "Orchestral Tools", "orchestral", "https://www.orchestraltools.com/", is_free=False, price_eur=849.0, description="Cordes orchestrales enregistrées à Berlin pour le cinéma."),
    plugin("8DIO Century", "8DIO", "orchestral", "https://8dio.com/", is_free=False, price_eur=399.0, description="Orchestre complet pour compositions épiques."),
    plugin("Cinesamples CineStrings SOLO", "Cinesamples", "orchestral", "https://cinesamples.com/", is_free=False, price_eur=199.0, description="Cordes solo cinématiques enregistrées à MGM Scoring Stage."),
    plugin("Fractal Audio Axe-Fx III", "Fractal Audio", "guitar", "https://www.fractalaudio.com/axe-fx-iii/", is_free=False, price_eur=2799.0, description="Processeur guitare hardware de référence avec éditeur logiciel."),
    plugin("Line 6 Helix Native", "Line 6", "guitar", "https://line6.com/helix/helixnative.html", is_free=False, price_eur=399.0, description="Plugin de la suite Helix avec modélisation d'amplis et d'effets."),
    plugin("Korg M1", "Korg", "synth", "https://www.korg.com/", is_free=False, price_eur=49.0, description="Émulation du synthé/workstation Korg M1 des années 90."),
    plugin("Roland Cloud Jupiter-8", "Roland", "synth", "https://roland.com/roland-cloud/", is_free=False, price_eur=20.0, description="Émulation du légendaire Jupiter-8 en abonnement Roland Cloud."),
    plugin("Waldorf Largo 2", "Waldorf Music", "synth", "https://www.waldorf-music.com/largo2", is_free=False, price_eur=179.0, description="Synthé wavetable polyphonique au son riche."),
    plugin("Applied Acoustics Lounge Lizard EP-4", "Applied Acoustics", "piano", "https://www.applied-acoustics.com/lounge-lizard-ep-4/", is_free=False, price_eur=199.0, description="Piano électrique Rhodes et Wurlitzer modélisé."),
    plugin("Modartt Pianoteq 8 Standard", "Modartt", "piano", "https://www.pianoteq.com/pianoteq-8", is_free=False, price_eur=159.0, description="Piano acoustique modélisé avec faible empreinte disque."),
    plugin("Keyscape", "Spectrasonics", "piano", "https://www.spectrasonics.net/products/keyscape/", is_free=False, price_eur=379.0, description="Collection de pianos et claviers rares échantillonnés."),
    plugin("Vienna Symphonic Library Synchron", "VSL", "orchestral", "https://www.vsl.co.at/", is_free=False, price_eur=299.0, description="Bibliothèque orchestrale viennoise haute qualité."),
    plugin("ProjectSAM Symphobia", "ProjectSAM", "orchestral", "https://projectsam.com/", is_free=False, price_eur=399.0, description="Orchestre cinématique avec articulations dramatiques."),
    plugin("Heavyocity Mosaic Keys", "Heavyocity", "piano", "https://heavyocity.com/product/mosaic-keys/", is_free=False, price_eur=199.0, description="Textures de claviers hybrides pour compositions modernes."),
    plugin("Sonic Academy KICK 2", "Sonic Academy", "drums", "https://sonicacademy.com/products/kick-2", is_free=False, price_eur=49.0, description="Synthé de kick dédié pour musiques électroniques."),
    plugin("Sonic Academy ANA 2", "Sonic Academy", "synth", "https://sonicacademy.com/products/ana-2", is_free=False, price_eur=99.0, description="Synthé polyphonique pour EDM et house."),
    plugin("Xfer Records Cthulhu", "Xfer Records", "utility", "https://xferrecords.com/products/cthulhu", is_free=False, price_eur=39.0, description="Générateur d'accords et arpégiateur MIDI créatif."),
    plugin("Xfer Records Nerve", "Xfer Records", "drums", "https://xferrecords.com/products/nerve", is_free=False, price_eur=99.0, description="Sampler de drums avec édition et resynthèse intégrées."),
    plugin("Loopcloud", "Loopmasters", "sampler", "https://www.loopcloud.com/", is_free=True, description="Gestionnaire de samples cloud avec plugin gratuit."),
    plugin("LANDR Samples", "LANDR", "sampler", "https://www.landr.com/", is_free=True, description="Plugin gratuit d'accès aux samples et presets LANDR."),
    plugin("Komplete 15 Select", "Native Instruments", "sampler", "https://www.native-instruments.com/en/products/komplete/bundles/komplete-15-select/", is_free=False, price_eur=199.0, description="Bundle NI avec synthés, effets et instruments sélectionnés."),
    plugin("Guitar Rig 7 Pro", "Native Instruments", "guitar", "https://www.native-instruments.com/en/products/komplete/guitar/guitar-rig-7-pro/", is_free=False, price_eur=199.0, description="Chaîne d'effets guitare complète avec modélisation d'amplis."),
    plugin("Raum", "Native Instruments", "reverb", "https://www.native-instruments.com/en/products/komplete/effects/raum/", is_free=True, description="Réverbération NI gratuite spacieuse et musicale."),
    plugin("Supercharger", "Native Instruments", "compressor", "https://www.native-instruments.com/en/products/komplete/effects/supercharger/", is_free=True, description="Compresseur vari-mu gratuit au son chaud."),
    plugin("Phasis", "Native Instruments", "modulation", "https://www.native-instruments.com/en/products/komplete/effects/phasis/", is_free=True, description="Phaser gratuit avec modulation flexible."),
    plugin("Bite", "Native Instruments", "distortion", "https://www.native-instruments.com/en/products/komplete/effects/bite/", is_free=True, description="Saturateur bitcrush gratuit pour textures agressives."),
    plugin("Dirt", "Native Instruments", "distortion", "https://www.native-instruments.com/en/products/komplete/effects/dirt/", is_free=True, description="Distorsion gratuite simple et efficace."),
    plugin("Flair", "Native Instruments", "modulation", "https://www.native-instruments.com/en/products/komplete/effects/flair/", is_free=True, description="Flanger gratuit avec feedback harmonique."),
    plugin("Choral", "Native Instruments", "modulation", "https://www.native-instruments.com/en/products/komplete/effects/choral/", is_free=True, description="Chorus gratuit inspiré des effets vintage."),
    plugin("Freak", "Native Instruments", "distortion", "https://www.native-instruments.com/en/products/komplete/effects/freak/", is_free=True, description="Triple distortion gratuite combinant wavefolding et modulation."),
    plugin("Molekular", "Native Instruments", "modulation", "https://www.native-instruments.com/en/products/komplete/effects/molekular/", is_free=True, description="Effets modulaires gratuits pour sound design."),
    plugin("SYMPHONY SERIES", "Native Instruments", "orchestral", "https://www.native-instruments.com/en/products/komplete/cinematic/symphony-series/", is_free=False, price_eur=999.0, description="Collection orchestrale complète Native Instruments."),
    plugin("Session Guitarist", "Native Instruments", "guitar", "https://www.native-instruments.com/en/products/komplete/guitar/session-guitarist/", is_free=False, price_eur=149.0, description="Guitares strumming et picking jouées par des session musicians."),
    plugin("Action Strings 2", "Native Instruments", "orchestral", "https://www.native-instruments.com/en/products/komplete/cinematic/action-strings-2/", is_free=False, price_eur=299.0, description="Cordes orchestrales dynamiques pour bandes-annonces."),
    plugin("Damage 2", "Heavyocity", "orchestral", "https://heavyocity.com/product/damage-2/", is_free=False, price_eur=399.0, description="Percussions orchestrales cinématiques et agressives."),
    plugin("Nexus", "reFX", "synth", "https://refx.com/nexus", is_free=False, price_eur=249.0, description="Rompler populaire pour leads et pads en production dance."),
    plugin("LFO Tool", "Xfer Records", "utility", "https://xferrecords.com/products/lfo-tool", is_free=False, price_eur=49.0, description="Outil de modulation LFO pour sidechain et effets rythmiques."),
    plugin("Endless Smile", "Dada Life", "utility", "https://www.pluginboutique.com/products/39-Endless-Smile", is_free=False, price_eur=49.0, description="Effet de build-up pour transitions en live et en club."),
    plugin("Kickstart 2", "Nicky Romero", "utility", "https://www.pluginboutique.com/products/2-Kickstart-2", is_free=False, price_eur=15.0, description="Sidechain pump automatique pour grooves EDM."),
    plugin("Trackspacer 2.5", "Wavesfactory", "utility", "https://www.wavesfactory.com/products/trackspacer", is_free=False, price_eur=59.0, description="Sidechain spectral pour dégager de l'espace dans le mix."),
    plugin("Vocal Rider", "Waves", "vocal", "https://www.waves.com/plugins/vocal-rider", is_free=False, price_eur=49.0, description="Automatisation du niveau vocal pour un mix constant."),
    plugin("CLA Vocals", "Waves", "vocal", "https://www.waves.com/plugins/cla-vocals", is_free=False, price_eur=49.0, description="Chaîne vocale complète signée Chris Lord-Alge."),
    plugin("Fresh Air", "Slate Digital", "eq", "https://slatedigital.com/fresh-air/", is_free=True, description="Enhancer aérien gratuit pour ajouter de la brillance."),
    plugin("Virtual Tape Machines", "Slate Digital", "distortion", "https://slatedigital.com/virtual-tape-machines/", is_free=False, price_eur=99.0, description="Émulation de machines à bandes Studer pour chaleur analogique."),
    plugin("Heatwave", "Slate Digital", "distortion", "https://slatedigital.com/heatwave/", is_free=True, description="Saturateur gratuit rapide pour ajouter de la présence."),
    plugin("KClip 3", "Kilohearts", "mastering", "https://kilohearts.com/products/kclip", is_free=False, price_eur=49.0, description="Clipper de mastering pour loudness contrôlée."),
    plugin("Multipass", "Kilohearts", "utility", "https://kilohearts.com/products/multipass", is_free=False, price_eur=99.0, description="Multiband multieffet pour traitement par bandes."),
    plugin("Snap Heap", "Kilohearts", "utility", "https://kilohearts.com/products/snap_heap", is_free=True, description="Rack d'effets modulaire gratuit de Kilohearts."),
    plugin("Phase Plant", "Kilohearts", "synth", "https://kilohearts.com/products/phase_plant", is_free=False, price_eur=149.0, description="Synthé génératif modulaire pour sound design avancé."),
    plugin("TAL-U-NO-LX", "TAL Software", "synth", "https://tal-software.com/products/tal-u-no-lx", is_free=False, price_eur=60.0, description="Émulation du Juno-60 avec chorus intégré."),
    plugin("TAL-BassLine", "TAL Software", "synth", "https://tal-software.com/products/tal-bassline", is_free=True, description="Synthé mono gratuit inspiré du SH-101 pour basses."),
    plugin("TAL-J-8", "TAL Software", "synth", "https://tal-software.com/products/tal-j-8", is_free=False, price_eur=60.0, description="Émulation du Roland Jupiter-8 au son iconique."),
    plugin("PG-8X", "Martin Lüders", "synth", "https://www.kvraudio.com/product/pg-8x-by-martin-luders", is_free=True, description="Émulation gratuite du Roland JX-8P polyphonique."),
    plugin("Versilian Upright No. 1", "Versilian Studios", "piano", "https://vis.versilstudios.com/vsco-community.html", is_free=True, description="Piano droit acoustique gratuit échantillonné."),
    plugin("Piano One", "Sound Magic", "piano", "https://www.soundmagic.com.cn/pianoone", is_free=True, description="Piano acoustique gratuit au son naturel."),
    plugin("Spitfire Soft Piano", "Spitfire Audio", "piano", "https://www.spitfireaudio.com/soft-piano", is_free=True, description="Piano feutré intime gratuit enregistré par Spitfire."),
    plugin("Ivy Audio Piano in 162", "Ivy Audio", "piano", "https://ivy-audio.com/", is_free=True, description="Piano Steinway gratuit échantillonné en détail."),
    plugin("Principessa", "Pianobook", "piano", "https://www.pianobook.co.uk/", is_free=True, description="Piano upright communautaire gratuit via Pianobook."),
    plugin("LABS Frozen Strings", "Spitfire Audio", "orchestral", "https://www.spitfireaudio.com/labs", is_free=True, description="Cordes orchestrales gelées et atmosphériques gratuites."),
    plugin("LABS Tape Piano", "Spitfire Audio", "piano", "https://www.spitfireaudio.com/labs", is_free=True, description="Piano enregistré sur bande magnétique, texture lo-fi."),
    plugin("LABS Synth Strings", "Spitfire Audio", "orchestral", "https://www.spitfireaudio.com/labs", is_free=True, description="Cordes synthétiques rétro gratuites."),
    plugin("LABS Mandolin", "Spitfire Audio", "guitar", "https://www.spitfireaudio.com/labs", is_free=True, description="Mandoline acoustique gratuite pour compositions folk."),
    plugin("LABS Electric Piano", "Spitfire Audio", "piano", "https://www.spitfireaudio.com/labs", is_free=True, description="Piano électrique vintage gratuit."),
    plugin("LABS Pedal Steel", "Spitfire Audio", "guitar", "https://www.spitfireaudio.com/labs", is_free=True, description="Pedal steel guitar gratuit pour ambiances country."),
    plugin("LABS Music Box", "Spitfire Audio", "utility", "https://www.spitfireaudio.com/labs", is_free=True, description="Boîte à musique gratuite pour textures délicates."),
    plugin("LABS Autoharp", "Spitfire Audio", "guitar", "https://www.spitfireaudio.com/labs", is_free=True, description="Autoharp gratuit pour ambiances folk et indie."),
    plugin("LABS Dulcimer", "Spitfire Audio", "guitar", "https://www.spitfireaudio.com/labs", is_free=True, description="Dulcimer gratuit aux sonorités cristallines."),
    plugin("LABS Lap Steel", "Spitfire Audio", "guitar", "https://www.spitfireaudio.com/labs", is_free=True, description="Lap steel gratuit pour ambiances hawaïennes et ambient."),
    plugin("LABS Hand Bells", "Spitfire Audio", "utility", "https://www.spitfireaudio.com/labs", is_free=True, description="Cloches à main gratuites pour effets lumineux."),
    plugin("LABS Tundra Atmos", "Spitfire Audio", "orchestral", "https://www.spitfireaudio.com/labs", is_free=True, description="Textures atmosphériques nordiques gratuites."),
    plugin("LABS Scary Strings", "Spitfire Audio", "orchestral", "https://www.spitfireaudio.com/labs", is_free=True, description="Cordes inquiétantes gratuites pour suspense."),
    plugin("LABS Moon Guitar", "Spitfire Audio", "guitar", "https://www.spitfireaudio.com/labs", is_free=True, description="Guitare acoustique lunaire gratuite et onirique."),
    plugin("LABS Harmonic Flute", "Spitfire Audio", "utility", "https://www.spitfireaudio.com/labs", is_free=True, description="Flûte harmonique gratuite pour textures aériennes."),
    plugin("LABS Bass Guitar", "Spitfire Audio", "guitar", "https://www.spitfireaudio.com/labs", is_free=True, description="Basse acoustique gratuite pour grooves organiques."),
    plugin("LABS Wurli", "Spitfire Audio", "piano", "https://www.spitfireaudio.com/labs", is_free=True, description="Wurlitzer électrique gratuit au son chaleureux."),
    plugin("LABS Amplified Cello Quartet", "Spitfire Audio", "orchestral", "https://www.spitfireaudio.com/labs", is_free=True, description="Quatuor de violoncelles amplifiés gratuit."),
    plugin("LABS Rare Flute", "Spitfire Audio", "utility", "https://www.spitfireaudio.com/labs", is_free=True, description="Flûte rare gratuite aux timbres uniques."),
    plugin("LABS Textural Piano", "Spitfire Audio", "piano", "https://www.spitfireaudio.com/labs", is_free=True, description="Piano textural gratuit pour ambiances expérimentales."),
    plugin("LABS Synth Choir", "Spitfire Audio", "vocal", "https://www.spitfireaudio.com/labs", is_free=True, description="Chœur synthétique gratuit pour pads vocaux."),
    plugin("LABS Electric Guitar", "Spitfire Audio", "guitar", "https://www.spitfireaudio.com/labs", is_free=True, description="Guitare électrique gratuite pour arpèges et nappes."),
    plugin("LABS Drum Machines", "Spitfire Audio", "drums", "https://www.spitfireaudio.com/labs", is_free=True, description="Machines à rythmes vintage gratuites."),
    plugin("LABS Glitch Drums", "Spitfire Audio", "drums", "https://www.spitfireaudio.com/labs", is_free=True, description="Batteries glitch gratuites pour productions IDM."),
    plugin("LABS Autograph Grand", "Spitfire Audio", "piano", "https://www.spitfireaudio.com/labs", is_free=True, description="Piano à queue concert gratuit."),
    plugin("LABS Peel Guitar", "Spitfire Audio", "guitar", "https://www.spitfireaudio.com/labs", is_free=True, description="Guitare acoustique peel gratuite au son cru."),
    plugin("LABS Organic Textures", "Spitfire Audio", "utility", "https://www.spitfireaudio.com/labs", is_free=True, description="Textures organiques gratuites pour soundscapes."),
    plugin("LABS Arctic Swells", "Spitfire Audio", "orchestral", "https://www.spitfireaudio.com/labs", is_free=True, description="Nappes orchestrales arctiques gratuites."),
    plugin("LABS Rare Violins", "Spitfire Audio", "orchestral", "https://www.spitfireaudio.com/labs", is_free=True, description="Violons rares gratuits pour mélodies expressives."),
    plugin("LABS Rare Woodwinds", "Spitfire Audio", "orchestral", "https://www.spitfireaudio.com/labs", is_free=True, description="Bois rares gratuits pour orchestrations."),
    plugin("LABS Rare Brass", "Spitfire Audio", "orchestral", "https://www.spitfireaudio.com/labs", is_free=True, description="Cuivres rares gratuits pour fanfares et textures."),
    plugin("LABS Rare Percussion", "Spitfire Audio", "drums", "https://www.spitfireaudio.com/labs", is_free=True, description="Percussions rares gratuites pour rythmes uniques."),
    plugin("LABS Rare Vocal", "Spitfire Audio", "vocal", "https://www.spitfireaudio.com/labs", is_free=True, description="Voix rares gratuites pour textures vocales."),
    plugin("LABS Rare Strings", "Spitfire Audio", "orchestral", "https://www.spitfireaudio.com/labs", is_free=True, description="Cordes rares gratuites pour arrangements."),
    plugin("LABS Rare Keys", "Spitfire Audio", "piano", "https://www.spitfireaudio.com/labs", is_free=True, description="Claviers rares gratuits pour textures vintage."),
    plugin("LABS Rare Synth", "Spitfire Audio", "synth", "https://www.spitfireaudio.com/labs", is_free=True, description="Synthés rares gratuits pour pads rétro."),
    plugin("LABS Rare Guitar", "Spitfire Audio", "guitar", "https://www.spitfireaudio.com/labs", is_free=True, description="Guitares rares gratuites pour sonorités uniques."),
    plugin("LABS Rare Bass", "Spitfire Audio", "guitar", "https://www.spitfireaudio.com/labs", is_free=True, description="Basses rares gratuites pour grooves profonds."),
    plugin("LABS Rare Drums", "Spitfire Audio", "drums", "https://www.spitfireaudio.com/labs", is_free=True, description="Batteries rares gratuites pour grooves atypiques."),
    plugin("LABS Rare FX", "Spitfire Audio", "utility", "https://www.spitfireaudio.com/labs", is_free=True, description="Effets sonores rares gratuits pour sound design."),
    plugin("LABS Rare Ambient", "Spitfire Audio", "utility", "https://www.spitfireaudio.com/labs", is_free=True, description="Ambiances rares gratuites pour compositions atmosphériques."),
    # --- Loop Packs ---
    plugin("Loopcloud", "Loopmasters", "loop_pack", "https://www.loopcloud.com/", is_free=True, formats=["WAV", "Standalone"], description="Plateforme cloud de loops et samples avec plugin gratuit et crédits mensuels."),
    plugin("Splice", "Splice", "loop_pack", "https://splice.com/", is_free=False, price_eur=13.0, formats=["WAV", "Standalone"], description="Abonnement à des millions de loops, one-shots et presets avec plugin DAW."),
    plugin("LANDR Samples", "LANDR", "loop_pack", "https://www.landr.com/", is_free=True, formats=["WAV", "Standalone"], description="Bibliothèque de samples et loops accessible via plugin gratuit."),
    plugin("Wave Alchemy Tapewave", "Wave Alchemy", "loop_pack", "https://www.wavealchemy.co.uk/tapewave/", is_free=False, price_eur=49.0, formats=["WAV"], description="Pack de loops vintage enregistrés sur bande magnétique."),
    plugin("Black Octopus Leviathan", "Black Octopus Sound", "loop_pack", "https://blackoctopus-sound.com/product/leviathan/", is_free=False, price_eur=79.0, formats=["WAV"], description="Collection massive de samples EDM, dubstep et bass music."),
    plugin("Sample Magic Raw Techno", "Sample Magic", "loop_pack", "https://www.samplemagic.com/", is_free=False, price_eur=29.0, formats=["WAV"], description="Loops et one-shots techno bruts pour production club."),
    plugin("Touch Loops Deep House", "Touch Loops", "loop_pack", "https://www.touchloops.com/", is_free=False, price_eur=25.0, formats=["WAV"], description="Loops deep house et grooves organiques."),
    plugin("Producer Loops Trap Essentials", "Producer Loops", "loop_pack", "https://www.producerloops.com/", is_free=False, price_eur=35.0, formats=["WAV"], description="Pack trap avec 808, hi-hats et mélodies."),
    plugin("Ghost Syndicate DnB Evolution", "Ghost Syndicate", "loop_pack", "https://www.ghostsyndicate.net/", is_free=False, price_eur=39.0, formats=["WAV"], description="Loops drum & bass modernes et basslines profondes."),
    plugin("Loopmasters Tech House", "Loopmasters", "loop_pack", "https://www.loopmasters.com/", is_free=False, price_eur=35.0, formats=["WAV"], description="Collection tech house avec tops, percussions et basses."),
    plugin("Beatport Sounds", "Beatport", "loop_pack", "https://www.beatport.com/sounds", is_free=False, price_eur=10.0, formats=["WAV"], description="Marketplace de packs loops et samples par genre."),
    plugin("Cymatics Infinity Loop Pack", "Cymatics", "loop_pack", "https://cymatics.fm/", is_free=True, formats=["WAV"], description="Pack de loops gratuit populaire en production électronique."),
    # --- Drum Kits ---
    plugin("Cymatics Free Drum Kits", "Cymatics", "drum_kit", "https://cymatics.fm/", is_free=True, formats=["WAV"], description="Kits de batterie gratuits : 808, trap, hip-hop et EDM."),
    plugin("Cymatics Infinity Drum Collection", "Cymatics", "drum_kit", "https://cymatics.fm/", is_free=False, price_eur=49.0, formats=["WAV"], description="Collection de one-shots et drum loops pour trap et EDM."),
    plugin("Splice Sounds Drums", "Splice", "drum_kit", "https://splice.com/sounds/packs", is_free=False, price_eur=13.0, formats=["WAV"], description="Des milliers de packs drums one-shot via abonnement Splice."),
    plugin("KSHMR Samples Vol. 4", "KSHMR", "drum_kit", "https://www.splice.com/kshmr", is_free=False, price_eur=40.0, formats=["WAV"], description="Kicks, snares et percussions du producteur KSHMR."),
    plugin("Native Instruments Battery 4", "Native Instruments", "drum_kit", "https://www.native-instruments.com/en/products/komplete/drums/battery-4/", is_free=False, price_eur=199.0, formats=["Battery", "Standalone"], description="Sampler de drums avec expansions et kits inclus."),
    plugin("XLN Audio AD2 Modern Rock", "XLN Audio", "drum_kit", "https://www.xlnaudio.com/products/addictive_drums_2", is_free=False, price_eur=49.0, formats=["WAV", "Standalone"], description="Expansion rock moderne pour Addictive Drums 2."),
    plugin("Sonic Academy KICK 2", "Sonic Academy", "drum_kit", "https://sonicacademy.com/products/kick-2", is_free=False, price_eur=49.0, formats=["VST3", "AU"], description="Synthé de kick pour créer des bass drums sur mesure."),
    plugin("Wave Alchemy Drum Tools", "Wave Alchemy", "drum_kit", "https://www.wavealchemy.co.uk/drum-tools/", is_free=False, price_eur=49.0, formats=["WAV"], description="One-shots de boîtes à rythmes vintage traitées."),
    plugin("Roland Cloud TR-808", "Roland", "drum_kit", "https://roland.com/roland-cloud/", is_free=False, price_eur=20.0, formats=["WAV", "Standalone"], description="Samples authentiques de la TR-808 via Roland Cloud."),
    plugin("Spitfire LABS Glitch Drums", "Spitfire Audio", "drum_kit", "https://www.spitfireaudio.com/labs", is_free=True, formats=["WAV", "Kontakt"], description="Batteries glitch gratuites pour productions expérimentales."),
    plugin("Spitfire LABS Drum Machines", "Spitfire Audio", "drum_kit", "https://www.spitfireaudio.com/labs", is_free=True, formats=["WAV", "Kontakt"], description="Machines à rythmes vintage gratuites."),
    plugin("808 Mafia Official Kits", "808 Mafia", "drum_kit", "https://www.beatport.com/", is_free=False, price_eur=30.0, formats=["WAV"], description="Kits trap et 808 distribués via boutiques officielles."),
    plugin("Slayed Gnarly", "Slayed", "drum_kit", "https://www.pluginboutique.com/", is_free=False, price_eur=35.0, formats=["WAV"], description="One-shots et loops trap agressifs pour production moderne."),
    # --- MIDI Kits ---
    plugin("Unison MIDI Chord Pack", "Unison", "midi_kit", "https://unison.audio/", is_free=False, price_eur=67.0, formats=["MIDI"], description="1200+ progressions d'accords MIDI pour tous genres."),
    plugin("Unison Free MIDI Pack", "Unison", "midi_kit", "https://unison.audio/", is_free=True, formats=["MIDI"], description="Pack MIDI gratuit avec mélodies et accords."),
    plugin("Cymatics MIDI Collection", "Cymatics", "midi_kit", "https://cymatics.fm/", is_free=True, formats=["MIDI"], description="Mélodies, accords et basslines MIDI gratuits."),
    plugin("WA Production MIDI Chord Pack", "W.A. Production", "midi_kit", "https://www.waproduction.com/", is_free=False, price_eur=29.0, formats=["MIDI"], description="Progressions d'accords MIDI pour EDM, pop et hip-hop."),
    plugin("Audiomodern Riffer", "AudioModern", "midi_kit", "https://audiomodern.com/shop/plugins/riffer/", is_free=False, price_eur=59.0, formats=["VST3", "AU", "MIDI"], description="Générateur de riffs et mélodies MIDI avec export."),
    plugin("Scaler 2", "Plugin Boutique", "midi_kit", "https://www.pluginboutique.com/products/2-Scaler-2", is_free=False, price_eur=59.0, formats=["VST3", "AU", "MIDI"], description="Assistant d'accords avec détection et suggestions MIDI."),
    plugin("Cthulhu", "Xfer Records", "midi_kit", "https://xferrecords.com/products/cthulhu", is_free=False, price_eur=39.0, formats=["VST3", "AU", "MIDI"], description="Générateur d'accords et arpégiateur MIDI créatif."),
    plugin("InstaComposer 3", "W.A. Production", "midi_kit", "https://www.waproduction.com/plugins/instacomposer-3", is_free=False, price_eur=59.0, formats=["VST3", "AU", "MIDI"], description="Génération de compositions MIDI assistée par IA."),
    plugin("Hooktheory Hookpad", "Hooktheory", "midi_kit", "https://www.hooktheory.com/hookpad", is_free=False, price_eur=50.0, formats=["MIDI", "Standalone"], description="Outil de composition avec export MIDI et théorie musicale."),
    plugin("Splice MIDI Packs", "Splice", "midi_kit", "https://splice.com/sounds/packs", is_free=False, price_eur=13.0, formats=["MIDI"], description="Packs MIDI mélodies, basses et accords via abonnement."),
    plugin("Producer Hive MIDI Vault", "Producer Hive", "midi_kit", "https://producerhive.com/", is_free=False, price_eur=25.0, formats=["MIDI"], description="Collection de MIDI packs pour house, techno et trap."),
    plugin("Loopmasters MIDI Packs", "Loopmasters", "midi_kit", "https://www.loopmasters.com/", is_free=False, price_eur=20.0, formats=["MIDI"], description="Packs MIDI par genre : house, DnB, hip-hop et plus."),
    # --- Bundles ---
    plugin("Komplete 15 Ultimate", "Native Instruments", "bundle", "https://www.native-instruments.com/en/products/komplete/bundles/komplete-15-ultimate/", is_free=False, price_eur=1799.0, formats=["VST3", "AU", "Standalone"], description="Bundle complet NI : 150+ instruments, effets et expansions."),
    plugin("Komplete 15 Standard", "Native Instruments", "bundle", "https://www.native-instruments.com/en/products/komplete/bundles/komplete-15-standard/", is_free=False, price_eur=599.0, formats=["VST3", "AU", "Standalone"], description="Bundle standard avec les essentiels Komplete 15."),
    plugin("Plugin Alliance Mega Bundle", "Plugin Alliance", "bundle", "https://www.plugin-alliance.com/", is_free=False, price_eur=249.0, formats=["VST3", "AU", "AAX"], description="Collection de plugins de mastering et mixage premium."),
    plugin("Waves Mercury Bundle", "Waves", "bundle", "https://www.waves.com/bundles/mercury", is_free=False, price_eur=599.0, formats=["VST3", "AU", "AAX"], description="Plus de 150 plugins Waves pour mixage, mastering et création."),
    plugin("iZotope Music Production Suite 6", "iZotope", "bundle", "https://www.izotope.com/en/shop/music-production-suite", is_free=False, price_eur=499.0, formats=["VST3", "AU", "AAX"], description="Suite complète : Ozone, Neutron, RX, Nectar et plus."),
    plugin("Arturia V Collection 10", "Arturia", "bundle", "https://www.arturia.com/products/software-instruments/v-collection/", is_free=False, price_eur=599.0, formats=["VST3", "AU", "Standalone"], description="32 émulations de synthés et pianos légendaires."),
    plugin("Slate Digital All Access Pass", "Slate Digital", "bundle", "https://slatedigital.com/all-access-pass/", is_free=False, price_eur=15.0, formats=["VST3", "AU", "AAX"], description="Abonnement mensuel à tous les plugins Slate Digital."),
    plugin("Softube Volume 1 Bundle", "Softube", "bundle", "https://www.softube.com/bundles", is_free=False, price_eur=199.0, formats=["VST3", "AU", "AAX"], description="Bundle d'effets et d'amplis Softube pour le mixage."),
    plugin("Reason Studios Reason+ Bundle", "Reason Studios", "bundle", "https://www.reasonstudios.com/reason", is_free=False, price_eur=20.0, formats=["VST3", "AU", "Standalone"], description="Abonnement Reason+ avec Rack, instruments et effets."),
    plugin("MeldaProduction MCompleteBundle", "MeldaProduction", "bundle", "https://www.meldaproduction.com/MCompleteBundle", is_free=False, price_eur=499.0, formats=["VST3", "AU", "AAX"], description="Bundle complet de 100+ plugins MeldaProduction."),
    plugin("Soundtoys 5", "Soundtoys", "bundle", "https://www.soundtoys.com/product/soundtoys-5/", is_free=False, price_eur=499.0, formats=["VST3", "AU", "AAX"], description="Collection complète des effets créatifs Soundtoys."),
    plugin("FabFilter Total Bundle", "FabFilter", "bundle", "https://www.fabfilter.com/bundles/total-bundle", is_free=False, price_eur=899.0, formats=["VST3", "AU", "AAX"], description="Tous les plugins FabFilter : EQ, compression, reverb, saturation."),
]


def deduplicate(plugins: list[dict]) -> list[dict]:
    seen: set[str] = set()
    unique: list[dict] = []
    for item in plugins:
        if item["slug"] in seen:
            continue
        seen.add(item["slug"])
        unique.append(item)
    return unique


def main() -> None:
    plugins = deduplicate(SEED_PLUGINS)
    payload = {
        "version": CATALOG_VERSION,
        "updatedAt": TODAY,
        "plugins": plugins,
    }
    for path in OUTPUT_PATHS:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Catalogue genere : {len(plugins)} plugins")
    for path in OUTPUT_PATHS:
        print(f"  -> {path}")


if __name__ == "__main__":
    main()
